allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  cpu-features: true
  esbuild: true
  less: true
  lmdb: true
  msgpackr-extract: true
  nx: true
  sharp: true
  ssh2: false
  unrs-resolver: true
