import type { CatalogPopularitySnapshot } from '@lego-platform/catalog/util';

// Generated by apps/catalog-popularity-sync. Do not edit by hand.
const catalogPopularitySnapshotPayload = String.raw`{
  "generatedAt": "2026-05-10T00:00:00.000Z",
  "windows": {
    "day": [],
    "week": []
  }
}`;

export const catalogPopularitySnapshot: CatalogPopularitySnapshot = JSON.parse(
  catalogPopularitySnapshotPayload,
) as CatalogPopularitySnapshot;
