import type { CatalogSnapshot } from '@lego-platform/catalog/util';

// Generated by apps/catalog-sync. Do not edit by hand.
const catalogSnapshotPayload = String.raw`{
  "source": "rebrickable-api-v3",
  "generatedAt": "2026-03-30T19:12:19.697Z",
  "setRecords": [
    {
      "canonicalId": "10316",
      "sourceSetNumber": "10316-1",
      "slug": "lord-of-the-rings-rivendell-10316",
      "name": "Lord of the Rings: Rivendell",
      "theme": "Icons",
      "releaseYear": 2023,
      "pieces": 6181,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/10316-1/132394.jpg"
    },
    {
      "canonicalId": "21348",
      "sourceSetNumber": "21348-1",
      "slug": "dungeons-and-dragons-red-dragons-tale-21348",
      "name": "Dungeons & Dragons: Red Dragon's Tale",
      "theme": "LEGO Ideas and CUUSOO",
      "releaseYear": 2024,
      "pieces": 3747,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/21348-1/138409.jpg"
    },
    {
      "canonicalId": "76269",
      "sourceSetNumber": "76269-1",
      "slug": "avengers-tower-76269",
      "name": "Avengers Tower",
      "theme": "Avengers",
      "releaseYear": 2023,
      "pieces": 5202,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/76269-1/129297.jpg"
    },
    {
      "canonicalId": "10305",
      "sourceSetNumber": "10305-1",
      "slug": "lion-knights-castle-10305",
      "name": "Lion Knights' Castle",
      "theme": "Icons",
      "releaseYear": 2022,
      "pieces": 4515,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/10305-1/152495.jpg"
    },
    {
      "canonicalId": "21338",
      "sourceSetNumber": "21338-1",
      "slug": "a-frame-cabin-21338",
      "name": "A-Frame Cabin",
      "theme": "LEGO Ideas and CUUSOO",
      "releaseYear": 2023,
      "pieces": 2083,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/21338-1/116515.jpg"
    },
    {
      "canonicalId": "10320",
      "sourceSetNumber": "10320-1",
      "slug": "eldorado-fortress-10320",
      "name": "Eldorado Fortress",
      "theme": "Icons",
      "releaseYear": 2023,
      "pieces": 2509,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/10320-1/127861.jpg"
    },
    {
      "canonicalId": "21335",
      "sourceSetNumber": "21335-1",
      "slug": "motorized-lighthouse-21335",
      "name": "Motorized Lighthouse",
      "theme": "LEGO Ideas and CUUSOO",
      "releaseYear": 2022,
      "pieces": 2065,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/21335-1/107884.jpg"
    },
    {
      "canonicalId": "10333",
      "sourceSetNumber": "10333-1",
      "slug": "the-lord-of-the-rings-barad-dur-10333",
      "name": "The Lord of the Rings: Barad-dûr",
      "theme": "Icons",
      "releaseYear": 2024,
      "pieces": 5478,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/10333-1/140959.jpg"
    },
    {
      "canonicalId": "10332",
      "sourceSetNumber": "10332-1",
      "slug": "medieval-town-square-10332",
      "name": "Medieval Town Square",
      "theme": "Icons",
      "releaseYear": 2024,
      "pieces": 3308,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/10332-1/137285.jpg"
    },
    {
      "canonicalId": "10315",
      "sourceSetNumber": "10315-1",
      "slug": "tranquil-garden-10315",
      "name": "Tranquil Garden",
      "theme": "Icons",
      "releaseYear": 2023,
      "pieces": 1363,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/10315-1/132380.jpg"
    },
    {
      "canonicalId": "21333",
      "sourceSetNumber": "21333-1",
      "slug": "the-starry-night-21333",
      "name": "The Starry Night",
      "theme": "LEGO Ideas and CUUSOO",
      "releaseYear": 2022,
      "pieces": 2316,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/21333-1/102873.jpg"
    },
    {
      "canonicalId": "21342",
      "sourceSetNumber": "21342-1",
      "slug": "the-insect-collection-21342",
      "name": "The Insect Collection",
      "theme": "LEGO Ideas and CUUSOO",
      "releaseYear": 2023,
      "pieces": 1111,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/21342-1/126471.jpg"
    },
    {
      "canonicalId": "10318",
      "sourceSetNumber": "10318-1",
      "slug": "concorde-10318",
      "name": "Concorde",
      "theme": "Icons",
      "releaseYear": 2023,
      "pieces": 2083,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/10318-1/132335.jpg"
    },
    {
      "canonicalId": "10331",
      "sourceSetNumber": "10331-1",
      "slug": "kingfisher-bird-10331",
      "name": "Kingfisher Bird",
      "theme": "Icons",
      "releaseYear": 2024,
      "pieces": 834,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/10331-1/135670.jpg"
    },
    {
      "canonicalId": "10341",
      "sourceSetNumber": "10341-1",
      "slug": "nasa-artemis-space-launch-system-10341",
      "name": "NASA Artemis Space Launch System",
      "theme": "Icons",
      "releaseYear": 2024,
      "pieces": 3601,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/10341-1/139647.jpg"
    },
    {
      "canonicalId": "21349",
      "sourceSetNumber": "21349-1",
      "slug": "tuxedo-cat-21349",
      "name": "Tuxedo Cat",
      "theme": "LEGO Ideas and CUUSOO",
      "releaseYear": 2024,
      "pieces": 1710,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/21349-1/140411.jpg"
    },
    {
      "canonicalId": "10300",
      "sourceSetNumber": "10300-1",
      "slug": "back-to-the-future-time-machine-10300",
      "name": "Back to the Future Time Machine",
      "theme": "Icons",
      "releaseYear": 2022,
      "pieces": 1872,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/10300-1/99954.jpg"
    },
    {
      "canonicalId": "10294",
      "sourceSetNumber": "10294-1",
      "slug": "titanic-10294",
      "name": "Titanic",
      "theme": "Icons",
      "releaseYear": 2021,
      "pieces": 9092,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/10294-1/93446.jpg"
    },
    {
      "canonicalId": "21061",
      "sourceSetNumber": "21061-1",
      "slug": "notre-dame-de-paris-21061",
      "name": "Notre-Dame de Paris",
      "theme": "Architecture",
      "releaseYear": 2024,
      "pieces": 4382,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/21061-1/140433.jpg"
    },
    {
      "canonicalId": "31208",
      "sourceSetNumber": "31208-1",
      "slug": "hokusai-the-great-wave-31208",
      "name": "Hokusai - The Great Wave",
      "theme": "LEGO Art",
      "releaseYear": 2023,
      "pieces": 1810,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/31208-1/131769.jpg"
    },
    {
      "canonicalId": "76419",
      "sourceSetNumber": "76419-1",
      "slug": "hogwarts-castle-and-grounds-76419",
      "name": "Hogwarts Castle and Grounds",
      "theme": "Harry Potter",
      "releaseYear": 2023,
      "pieces": 2660,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/76419-1/123597.jpg"
    },
    {
      "canonicalId": "43222",
      "sourceSetNumber": "43222-1",
      "slug": "disney-castle-43222",
      "name": "Disney Castle",
      "theme": "Disney",
      "releaseYear": 2023,
      "pieces": 4837,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/43222-1/130721.jpg"
    },
    {
      "canonicalId": "75313",
      "sourceSetNumber": "75313-1",
      "slug": "at-at-75313",
      "name": "AT-AT",
      "theme": "Ultimate Collector Series",
      "releaseYear": 2021,
      "pieces": 6785,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/75313-1/94568.jpg"
    },
    {
      "canonicalId": "21345",
      "sourceSetNumber": "21345-1",
      "slug": "polaroid-onestep-sx-70-21345",
      "name": "Polaroid OneStep SX-70",
      "theme": "LEGO Ideas and CUUSOO",
      "releaseYear": 2024,
      "pieces": 516,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/21345-1/134647.jpg"
    },
    {
      "canonicalId": "10326",
      "sourceSetNumber": "10326-1",
      "slug": "natural-history-museum-10326",
      "name": "Natural History Museum",
      "theme": "Modular Buildings",
      "releaseYear": 2023,
      "pieces": 4015,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/10326-1/129017.jpg"
    },
    {
      "canonicalId": "10323",
      "sourceSetNumber": "10323-1",
      "slug": "pac-man-arcade-10323",
      "name": "PAC-MAN Arcade",
      "theme": "Icons",
      "releaseYear": 2023,
      "pieces": 2651,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/10323-1/132286.jpg"
    },
    {
      "canonicalId": "10306",
      "sourceSetNumber": "10306-1",
      "slug": "atari-2600-10306",
      "name": "Atari 2600",
      "theme": "Icons",
      "releaseYear": 2022,
      "pieces": 2532,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/10306-1/105658.jpg"
    },
    {
      "canonicalId": "10280",
      "sourceSetNumber": "10280-1",
      "slug": "flower-bouquet-10280",
      "name": "Flower Bouquet",
      "theme": "Botanicals",
      "releaseYear": 2021,
      "pieces": 756,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/10280-1/148035.jpg"
    },
    {
      "canonicalId": "10311",
      "sourceSetNumber": "10311-1",
      "slug": "orchid-10311",
      "name": "Orchid",
      "theme": "Botanicals",
      "releaseYear": 2022,
      "pieces": 608,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/10311-1/148060.jpg"
    },
    {
      "canonicalId": "21327",
      "sourceSetNumber": "21327-1",
      "slug": "typewriter-21327",
      "name": "Typewriter",
      "theme": "LEGO Ideas and CUUSOO",
      "releaseYear": 2021,
      "pieces": 2080,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/21327-1/89136.jpg"
    },
    {
      "canonicalId": "21343",
      "sourceSetNumber": "21343-1",
      "slug": "viking-village-21343",
      "name": "Viking Village",
      "theme": "LEGO Ideas and CUUSOO",
      "releaseYear": 2023,
      "pieces": 2104,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/21343-1/127226.jpg"
    },
    {
      "canonicalId": "42115",
      "sourceSetNumber": "42115-1",
      "slug": "lamborghini-sian-fkp-37-42115",
      "name": "Lamborghini Sián FKP 37",
      "theme": "Technic",
      "releaseYear": 2020,
      "pieces": 3696,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/42115-1/63711.jpg"
    },
    {
      "canonicalId": "42143",
      "sourceSetNumber": "42143-1",
      "slug": "ferrari-daytona-sp3-42143",
      "name": "Ferrari Daytona SP3",
      "theme": "Technic",
      "releaseYear": 2022,
      "pieces": 3778,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/42143-1/103001.jpg"
    },
    {
      "canonicalId": "71411",
      "sourceSetNumber": "71411-1",
      "slug": "the-mighty-bowser-71411",
      "name": "The Mighty Bowser",
      "theme": "Super Mario",
      "releaseYear": 2022,
      "pieces": 2807,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/71411-1/104617.jpg"
    },
    {
      "canonicalId": "71741",
      "sourceSetNumber": "71741-1",
      "slug": "ninjago-city-gardens-71741",
      "name": "NINJAGO City Gardens",
      "theme": "Ninjago",
      "releaseYear": 2021,
      "pieces": 5710,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/71741-1/80116.jpg"
    },
    {
      "canonicalId": "76218",
      "sourceSetNumber": "76218-1",
      "slug": "sanctum-sanctorum-76218",
      "name": "Sanctum Sanctorum",
      "theme": "The Infinity Saga",
      "releaseYear": 2022,
      "pieces": 2713,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/76218-1/104030.jpg"
    },
    {
      "canonicalId": "76956",
      "sourceSetNumber": "76956-1",
      "slug": "t-rex-breakout-76956",
      "name": "T. rex Breakout",
      "theme": "Jurassic World",
      "releaseYear": 2022,
      "pieces": 1212,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/76956-1/142003.jpg"
    },
    {
      "canonicalId": "75331",
      "sourceSetNumber": "75331-1",
      "slug": "the-razor-crest-75331",
      "name": "The Razor Crest",
      "theme": "Ultimate Collector Series",
      "releaseYear": 2022,
      "pieces": 6187,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/75331-1/110279.jpg"
    },
    {
      "canonicalId": "76417",
      "sourceSetNumber": "76417-1",
      "slug": "gringotts-wizarding-bank-collectors-edition-76417",
      "name": "Gringotts Wizarding Bank – Collectors' Edition",
      "theme": "Harry Potter",
      "releaseYear": 2023,
      "pieces": 4809,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/76417-1/127873.jpg"
    }
  ]
}`;

export const catalogSnapshot: CatalogSnapshot = JSON.parse(
  catalogSnapshotPayload,
) as CatalogSnapshot;
