import type { CatalogSnapshot } from '@lego-platform/catalog/util';

// Generated by apps/catalog-sync. Do not edit by hand.
export const catalogSnapshot: CatalogSnapshot = {
  "source": "seeded-catalog-snapshot",
  "generatedAt": "2026-03-28T00:00:00.000Z",
  "setRecords": [
    {
      "canonicalId": "10316",
      "sourceSetNumber": "10316-1",
      "slug": "rivendell-10316",
      "name": "Rivendell",
      "theme": "Icons",
      "releaseYear": 2023,
      "pieces": 6167
    },
    {
      "canonicalId": "21348",
      "sourceSetNumber": "21348-1",
      "slug": "dungeons-and-dragons-red-dragons-tale-21348",
      "name": "Dungeons & Dragons: Red Dragon's Tale",
      "theme": "Ideas",
      "releaseYear": 2024,
      "pieces": 3745
    },
    {
      "canonicalId": "76269",
      "sourceSetNumber": "76269-1",
      "slug": "avengers-tower-76269",
      "name": "Avengers Tower",
      "theme": "Marvel",
      "releaseYear": 2023,
      "pieces": 5201
    }
  ]
};
