import type { CatalogSnapshot } from '@lego-platform/catalog/util';

// Generated by apps/catalog-sync. Do not edit by hand.
export const catalogSnapshot: CatalogSnapshot = {
  "source": "rebrickable-api-v3",
  "generatedAt": "2026-03-29T22:00:00.000Z",
  "setRecords": [
    {
      "canonicalId": "10316",
      "sourceSetNumber": "10316-1",
      "slug": "lord-of-the-rings-rivendell-10316",
      "name": "Lord of the Rings: Rivendell",
      "theme": "Icons",
      "releaseYear": 2023,
      "pieces": 6181,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/10316-1/132394.jpg"
    },
    {
      "canonicalId": "21348",
      "sourceSetNumber": "21348-1",
      "slug": "dungeons-and-dragons-red-dragons-tale-21348",
      "name": "Dungeons & Dragons: Red Dragon's Tale",
      "theme": "LEGO Ideas and CUUSOO",
      "releaseYear": 2024,
      "pieces": 3747,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/21348-1/138409.jpg"
    },
    {
      "canonicalId": "76269",
      "sourceSetNumber": "76269-1",
      "slug": "avengers-tower-76269",
      "name": "Avengers Tower",
      "theme": "Avengers",
      "releaseYear": 2023,
      "pieces": 5202,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/76269-1/129297.jpg"
    },
    {
      "canonicalId": "10305",
      "sourceSetNumber": "10305-1",
      "slug": "lion-knights-castle-10305",
      "name": "Lion Knights' Castle",
      "theme": "Icons",
      "releaseYear": 2022,
      "pieces": 4515,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/10305-1/152495.jpg"
    },
    {
      "canonicalId": "21338",
      "sourceSetNumber": "21338-1",
      "slug": "a-frame-cabin-21338",
      "name": "A-Frame Cabin",
      "theme": "LEGO Ideas and CUUSOO",
      "releaseYear": 2023,
      "pieces": 2083,
      "imageUrl": "https://cdn.rebrickable.com/media/sets/21338-1/116515.jpg"
    },
    {
      "canonicalId": "10320",
      "sourceSetNumber": "10320-1",
      "slug": "eldorado-fortress-10320",
      "name": "Eldorado Fortress",
      "theme": "Icons",
      "releaseYear": 2023,
      "pieces": 2509,
      "imageUrl": "https://cdn.rebrickable.com/media/thumbs/sets/10320-1/127861.jpg/1000x800p.jpg"
    },
    {
      "canonicalId": "21335",
      "sourceSetNumber": "21335-1",
      "slug": "motorized-lighthouse-21335",
      "name": "Motorized Lighthouse",
      "theme": "LEGO Ideas and CUUSOO",
      "releaseYear": 2022,
      "pieces": 2065,
      "imageUrl": "https://cdn.rebrickable.com/media/thumbs/sets/21335-1/107884.jpg/1000x800p.jpg"
    },
    {
      "canonicalId": "10333",
      "sourceSetNumber": "10333-1",
      "slug": "the-lord-of-the-rings-barad-dur-10333",
      "name": "The Lord of the Rings: Barad-dur",
      "theme": "Icons",
      "releaseYear": 2024,
      "pieces": 5471,
      "imageUrl": "https://cdn.rebrickable.com/media/thumbs/sets/10333-1/140959.jpg/1000x800p.jpg"
    },
    {
      "canonicalId": "10332",
      "sourceSetNumber": "10332-1",
      "slug": "medieval-town-square-10332",
      "name": "Medieval Town Square",
      "theme": "Icons",
      "releaseYear": 2024,
      "pieces": 3304,
      "imageUrl": "https://cdn.rebrickable.com/media/thumbs/sets/10332-1/137285.jpg/1000x800p.jpg"
    },
    {
      "canonicalId": "10315",
      "sourceSetNumber": "10315-1",
      "slug": "tranquil-garden-10315",
      "name": "Tranquil Garden",
      "theme": "Icons",
      "releaseYear": 2023,
      "pieces": 1363,
      "imageUrl": "https://cdn.rebrickable.com/media/thumbs/sets/10315-1/132380.jpg/1000x800p.jpg"
    },
    {
      "canonicalId": "21333",
      "sourceSetNumber": "21333-1",
      "slug": "the-starry-night-21333",
      "name": "The Starry Night",
      "theme": "LEGO Ideas and CUUSOO",
      "releaseYear": 2022,
      "pieces": 2316,
      "imageUrl": "https://cdn.rebrickable.com/media/thumbs/sets/21333-1/102873.jpg/1000x800p.jpg"
    },
    {
      "canonicalId": "21342",
      "sourceSetNumber": "21342-1",
      "slug": "the-insect-collection-21342",
      "name": "The Insect Collection",
      "theme": "LEGO Ideas and CUUSOO",
      "releaseYear": 2023,
      "pieces": 1111,
      "imageUrl": "https://cdn.rebrickable.com/media/thumbs/sets/21342-1/126471.jpg/1000x800p.jpg"
    }
  ]
};
