import type { CatalogSyncManifest } from '@lego-platform/catalog/util';

// Generated by apps/catalog-sync. Do not edit by hand.
export const catalogSyncManifest: CatalogSyncManifest = {
  source: 'rebrickable-api-v3',
  generatedAt: '2026-03-29T07:20:35.929Z',
  recordCount: 5,
  homepageFeaturedSetIds: ['10316', '21348', '76269'],
  notes:
    'Generated from the curated Rebrickable sync scope. Collector-facing overlays remain local.',
};
