export const DUTCH_REGION_CODE = 'NL';
export const EURO_CURRENCY_CODE = 'EUR';
export const NEW_OFFER_CONDITION = 'new';
export const PRICING_HISTORY_TABLE = 'pricing_daily_set_history';
export const PRICE_HISTORY_WINDOW_DAYS = 30;

export type PricingRegionCode = typeof DUTCH_REGION_CODE;
export type PricingCurrencyCode = typeof EURO_CURRENCY_CODE;
export type PricingCondition = typeof NEW_OFFER_CONDITION;
export type PricingAvailability =
  | 'in_stock'
  | 'limited'
  | 'out_of_stock'
  | 'preorder'
  | 'unknown';

export interface PricingObservation {
  availability: PricingAvailability;
  condition: PricingCondition;
  currencyCode: PricingCurrencyCode;
  merchantId: string;
  observedAt: string;
  regionCode: PricingRegionCode;
  setId: string;
  totalPriceMinor: number;
}

export interface PricePanelSnapshot {
  condition: PricingCondition;
  currencyCode: PricingCurrencyCode;
  deltaMinor?: number;
  headlinePriceMinor: number;
  lowestAvailabilityLabel?: string;
  lowestMerchantId: string;
  lowestMerchantName: string;
  merchantCount: number;
  observedAt: string;
  referencePriceMinor?: number;
  regionCode: PricingRegionCode;
  setId: string;
}

export interface FeaturedSetPriceContext {
  availabilityLabel?: string;
  currencyCode: PricingCurrencyCode;
  deltaMinor?: number;
  headlinePriceMinor: number;
  merchantCount: number;
  merchantName: string;
  observedAt: string;
  referencePriceMinor?: number;
  setId: string;
}

export interface PricingSyncManifest {
  generatedAt: string;
  notes?: string;
  observationCount: number;
  setCount: number;
  source: string;
}

export interface PriceHistoryPoint {
  condition: PricingCondition;
  currencyCode: PricingCurrencyCode;
  headlinePriceMinor: number;
  lowestMerchantId?: string;
  observedAt: string;
  recordedOn: string;
  referencePriceMinor?: number;
  regionCode: PricingRegionCode;
  setId: string;
}

export interface PriceHistorySummary {
  averagePriceMinor: number;
  currencyCode: PricingCurrencyCode;
  currentHeadlinePriceMinor: number;
  deltaVsAverageMinor: number;
  highPriceMinor: number;
  lowPriceMinor: number;
  pointCount: number;
}

export interface TrackedPriceSummary {
  currencyCode: PricingCurrencyCode;
  currentHeadlinePriceMinor: number;
  deltaVsTrackedHighMinor: number;
  deltaVsTrackedLowMinor: number;
  pointCount: number;
  trackedHighPriceMinor: number;
  trackedLowPriceMinor: number;
  trackedSinceRecordedOn: string;
}

export function getPriceDirection(deltaMinor?: number): 'up' | 'down' | 'flat' {
  if (typeof deltaMinor !== 'number' || deltaMinor === 0) {
    return 'flat';
  }

  return deltaMinor > 0 ? 'up' : 'down';
}

export function formatPriceMinor({
  currencyCode,
  locale = 'nl-NL',
  minorUnits,
}: {
  currencyCode: string;
  locale?: string;
  minorUnits: number;
}): string {
  return new Intl.NumberFormat(locale, {
    style: 'currency',
    currency: currencyCode,
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(minorUnits / 100);
}

function renderPricingGeneratedModule<
  T extends
    | PricingSyncManifest
    | readonly PricePanelSnapshot[]
    | readonly PricingObservation[],
>({
  exportName,
  importNames,
  typeAnnotation,
  payload,
}: {
  exportName:
    | 'pricePanelSnapshots'
    | 'pricingObservations'
    | 'pricingSyncManifest';
  importNames: string[];
  typeAnnotation: string;
  payload: T;
}): string {
  return `import type { ${importNames.join(', ')} } from '@lego-platform/pricing/util';

// Generated by apps/commerce-sync. Do not edit by hand.
export const ${exportName}: ${typeAnnotation} = ${JSON.stringify(payload, null, 2)};
`;
}

export function renderPricingObservationsModule(
  pricingObservations: readonly PricingObservation[],
): string {
  return renderPricingGeneratedModule({
    exportName: 'pricingObservations',
    importNames: ['PricingObservation'],
    typeAnnotation: 'readonly PricingObservation[]',
    payload: pricingObservations,
  });
}

export function renderPricePanelSnapshotsModule(
  pricePanelSnapshots: readonly PricePanelSnapshot[],
): string {
  return renderPricingGeneratedModule({
    exportName: 'pricePanelSnapshots',
    importNames: ['PricePanelSnapshot'],
    typeAnnotation: 'readonly PricePanelSnapshot[]',
    payload: pricePanelSnapshots,
  });
}

export function renderPricingSyncManifestModule(
  pricingSyncManifest: PricingSyncManifest,
): string {
  return renderPricingGeneratedModule({
    exportName: 'pricingSyncManifest',
    importNames: ['PricingSyncManifest'],
    typeAnnotation: 'PricingSyncManifest',
    payload: pricingSyncManifest,
  });
}
