import {
  DUTCH_REGION_CODE,
  EURO_CURRENCY_CODE,
  NEW_OFFER_CONDITION,
  type PricingAvailability,
  type PricingCondition,
  type PricingCurrencyCode,
  type PricingRegionCode,
} from '@lego-platform/pricing/util';

export interface PricingObservationSeed {
  availability: PricingAvailability;
  condition: PricingCondition;
  currencyCode: PricingCurrencyCode;
  merchantId: string;
  merchantProductUrl: string;
  observedAt: string;
  regionCode: PricingRegionCode;
  setId: string;
  totalPriceMinor: number;
}

// Keep merchant product destinations curated per set.
// Do not synthesize product URLs from set ids or merchant naming patterns.
export const curatedDutchPricingObservationSeeds: readonly PricingObservationSeed[] =
  [
    {
      setId: '10316',
      merchantId: 'bol',
      merchantProductUrl:
        'https://www.bol.com/nl/nl/p/lego-10316-the-lord-of-the-rings-rivendell/9300000144104277/',
      totalPriceMinor: 46999,
      availability: 'in_stock',
      observedAt: '2026-03-31T09:00:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '10316',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/the-lord-of-the-rings-rivendell-10316',
      totalPriceMinor: 49999,
      availability: 'in_stock',
      observedAt: '2026-03-31T09:08:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '21348',
      merchantId: 'bol',
      merchantProductUrl:
        'https://www.bol.com/nl/nl/p/lego-ideas-dungeons-dragons-het-verhaal-van-de-rode-draak-21348/9300000175725314/',
      totalPriceMinor: 33499,
      availability: 'in_stock',
      observedAt: '2026-03-31T09:12:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '21348',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/dungeons-dragons-red-dragons-tale-21348',
      totalPriceMinor: 35999,
      availability: 'in_stock',
      observedAt: '2026-03-31T09:20:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '10305',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/lion-knights-castle-10305',
      totalPriceMinor: 38999,
      availability: 'in_stock',
      observedAt: '2026-03-31T09:40:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '10332',
      merchantId: 'bol',
      merchantProductUrl:
        'https://www.bol.com/nl/nl/p/lego-icons-middeleeuws-stadsplein-10332/9300000173010312/',
      totalPriceMinor: 21499,
      availability: 'in_stock',
      observedAt: '2026-03-31T09:44:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '10332',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/medieval-town-square-10332',
      totalPriceMinor: 22999,
      availability: 'in_stock',
      observedAt: '2026-03-31T09:52:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '10333',
      merchantId: 'amazon-nl',
      merchantProductUrl:
        'https://www.amazon.com/LEGO-Icons-Lord-Rings-Memorabilia/dp/B0D72T1NTC?crid=N5799A29802E&dib=eyJ2IjoiMSJ9.QOZUuLSu39FgmrLjkKSkJvLVx7CLrRfYbRxcnFWF067JHw9uNVawu3s15lcLDzXwc9inzcahMme44UDJizpcqcrlI0niMdJV0e0ULc-DOWO-2lCuJHRjWK90xQ5JFYrjVvNYR4H-ZKs-TBpw1gTl6o_um45zfFUZ8ftC-DM89ALOeaZ5yWMqmQiawHvE7fUCTgaPXyKk-qoJwjQgOU_mfDcHdEOCOeow22yrmOl42fvGYFDAxvHLGB7b_J-qHCVMZS02-p1y4X0s0xRrzzze2I9B-SntuTmfDTqf-wtnPSk.9BTD3SU-6bF1E9FZOUGughUyhfe-rif4P5PSIbFphjw&dib_tag=se&keywords=lego+barad+dur&qid=1775672707&sprefix=lego+barad%2Caps%2C251&sr=8-1&linkCode=ll2&tag=brickhunt-20&linkId=e2b959c2dd98eb1f812205243b15e2ef&language=en_US&ref_=as_li_ss_tl',
      totalPriceMinor: 42999,
      availability: 'in_stock',
      observedAt: '2026-03-31T09:56:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '10333',
      merchantId: 'bol',
      merchantProductUrl:
        'https://www.bol.com/nl/nl/p/lego-de-lord-of-the-rings-barad-majoor-10333/9300000180281419/',
      totalPriceMinor: 43999,
      availability: 'in_stock',
      observedAt: '2026-03-31T09:56:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '10333',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/the-lord-of-the-rings-barad-dur-10333',
      totalPriceMinor: 45999,
      availability: 'in_stock',
      observedAt: '2026-03-31T10:04:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '10294',
      merchantId: 'lego-nl',
      merchantProductUrl: 'https://www.lego.com/nl-nl/product/titanic-10294',
      totalPriceMinor: 65999,
      availability: 'in_stock',
      observedAt: '2026-03-31T10:32:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '21061',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/notre-dame-de-paris-21061',
      totalPriceMinor: 21999,
      availability: 'in_stock',
      observedAt: '2026-03-31T10:36:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '21333',
      merchantId: 'bol',
      merchantProductUrl:
        'https://www.bol.com/nl/nl/p/lego-ideas-vincent-van-gogh-sterrennacht-21333/9300000070995024/',
      totalPriceMinor: 14999,
      availability: 'in_stock',
      observedAt: '2026-03-31T10:08:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '21333',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/vincent-van-gogh-the-starry-night-21333',
      totalPriceMinor: 16999,
      availability: 'in_stock',
      observedAt: '2026-03-31T10:16:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '21349',
      merchantId: 'bol',
      merchantProductUrl:
        'https://www.bol.com/nl/nl/p/lego-ideas-zwart-witte-kat-21349/9300000173010346/',
      totalPriceMinor: 9499,
      availability: 'in_stock',
      observedAt: '2026-03-31T10:20:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '21349',
      merchantId: 'lego-nl',
      merchantProductUrl: 'https://www.lego.com/nl-nl/product/tuxedo-cat-21349',
      totalPriceMinor: 10999,
      availability: 'in_stock',
      observedAt: '2026-03-31T10:28:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '76178',
      merchantId: 'bol',
      merchantProductUrl:
        'https://www.bol.com/nl/nl/p/lego-spider-man-daily-bugle-76178/9300000040027340/',
      totalPriceMinor: 32999,
      availability: 'in_stock',
      observedAt: '2026-03-31T10:44:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '76178',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/daily-bugle-76178',
      totalPriceMinor: 33999,
      availability: 'in_stock',
      observedAt: '2026-03-31T10:48:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '75367',
      merchantId: 'bol',
      merchantProductUrl:
        'https://www.bol.com/nl/nl/p/lego-star-wars-venator-class-republic-attack-cruiser-75367/9300000161235312/',
      totalPriceMinor: 63999,
      availability: 'in_stock',
      observedAt: '2026-03-31T10:52:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '75367',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/venator-class-republic-attack-cruiser-75367',
      totalPriceMinor: 64999,
      availability: 'in_stock',
      observedAt: '2026-03-31T10:56:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '21350',
      merchantId: 'bol',
      merchantProductUrl:
        'https://www.bol.com/nl/nl/p/lego-21350-jaws-lego-ideas/9300000185934485/',
      totalPriceMinor: 15499,
      availability: 'in_stock',
      observedAt: '2026-03-31T11:00:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '21350',
      merchantId: 'lego-nl',
      merchantProductUrl: 'https://www.lego.com/nl-nl/product/jaws-21350',
      totalPriceMinor: 15999,
      availability: 'in_stock',
      observedAt: '2026-03-31T11:04:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '10317',
      merchantId: 'bol',
      merchantProductUrl:
        'https://www.bol.com/nl/nl/p/lego-10317-land-rover-classic-defender-90/9300000137836645/',
      totalPriceMinor: 22999,
      availability: 'in_stock',
      observedAt: '2026-03-31T11:08:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '10317',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/land-rover-classic-defender-90-10317',
      totalPriceMinor: 23999,
      availability: 'in_stock',
      observedAt: '2026-03-31T11:12:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '76269',
      merchantId: 'bol',
      merchantProductUrl:
        'https://www.bol.com/nl/nl/p/lego-avengers-toren-lego-marvel/9300000168131115/',
      totalPriceMinor: 46999,
      availability: 'in_stock',
      observedAt: '2026-03-31T09:24:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '76269',
      merchantId: 'intertoys',
      merchantProductUrl:
        'https://www.intertoys.nl/lego-marvel-avengers-toren-76269',
      totalPriceMinor: 47999,
      availability: 'limited',
      observedAt: '2026-03-31T09:30:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '76269',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/avengers-tower-76269',
      totalPriceMinor: 49999,
      availability: 'in_stock',
      observedAt: '2026-03-31T09:36:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '75355',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/x-wing-starfighter-75355',
      totalPriceMinor: 23999,
      availability: 'in_stock',
      observedAt: '2026-03-31T11:16:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '75397',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/jabbas-sail-barge-75397',
      totalPriceMinor: 49999,
      availability: 'in_stock',
      observedAt: '2026-03-31T11:20:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '76429',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/talking-sorting-hat-76429',
      totalPriceMinor: 9999,
      availability: 'in_stock',
      observedAt: '2026-03-31T11:24:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '76435',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/hogwarts-castle-the-great-hall-76435',
      totalPriceMinor: 19999,
      availability: 'in_stock',
      observedAt: '2026-03-31T11:28:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '76294',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/x-men-the-x-mansion-76294',
      totalPriceMinor: 32999,
      availability: 'in_stock',
      observedAt: '2026-03-31T11:32:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '10335',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/the-endurance-10335',
      totalPriceMinor: 26999,
      availability: 'in_stock',
      observedAt: '2026-03-31T11:36:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '10327',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/dune-atreides-royal-ornithopter-10327',
      totalPriceMinor: 16499,
      availability: 'in_stock',
      observedAt: '2026-03-31T11:40:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '42171',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/mercedes-amg-f1-w14-e-performance-42171',
      totalPriceMinor: 21999,
      availability: 'in_stock',
      observedAt: '2026-03-31T11:44:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '42172',
      merchantId: 'lego-nl',
      merchantProductUrl: 'https://www.lego.com/nl-nl/product/mclaren-p1-42172',
      totalPriceMinor: 44999,
      availability: 'in_stock',
      observedAt: '2026-03-31T11:48:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '10328',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/bouquet-of-roses-10328',
      totalPriceMinor: 5999,
      availability: 'in_stock',
      observedAt: '2026-03-31T11:52:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '75398',
      merchantId: 'bol',
      merchantProductUrl:
        'https://www.bol.com/nl/nl/p/lego-star-wars-c-3po-decoratie-bouwpakket-met-droid-figuur-75398/9300000175725370/',
      totalPriceMinor: 8599,
      availability: 'in_stock',
      observedAt: '2026-04-03T09:00:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '75398',
      merchantId: 'lego-nl',
      merchantProductUrl: 'https://www.lego.com/nl-nl/product/c-3po-75398',
      totalPriceMinor: 13999,
      availability: 'in_stock',
      observedAt: '2026-04-03T09:04:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '76453',
      merchantId: 'bol',
      merchantProductUrl:
        'https://www.bol.com/nl/nl/p/lego-harry-potter-villa-malfidus-76453/9300000187249771/',
      totalPriceMinor: 11249,
      availability: 'in_stock',
      observedAt: '2026-04-03T09:08:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '76453',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/malfoy-manor-76453',
      totalPriceMinor: 14999,
      availability: 'in_stock',
      observedAt: '2026-04-03T09:12:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '76313',
      merchantId: 'bol',
      merchantProductUrl:
        'https://www.bol.com/nl/nl/p/lego-marvel-logo-minifiguren-superhelden-speelset-76313/9300000205068081/',
      totalPriceMinor: 8499,
      availability: 'in_stock',
      observedAt: '2026-04-03T09:16:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '76313',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/marvel-logo-minifigures-76313',
      totalPriceMinor: 9999,
      availability: 'in_stock',
      observedAt: '2026-04-03T09:20:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '10354',
      merchantId: 'bol',
      merchantProductUrl:
        'https://www.bol.com/nl/nl/p/lego-icons-the-lord-of-the-rings-de-gouw-bouwset-10354/9300000223017341/',
      totalPriceMinor: 24643,
      availability: 'in_stock',
      observedAt: '2026-04-03T09:24:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '10354',
      merchantId: 'lego-nl',
      merchantProductUrl: 'https://www.lego.com/nl-nl/product/the-shire-10354',
      totalPriceMinor: 26999,
      availability: 'in_stock',
      observedAt: '2026-04-03T09:28:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '42177',
      merchantId: 'bol',
      merchantProductUrl:
        'https://www.bol.com/nl/nl/p/lego-technic-mercedes-benz-g-500-professional-line-42177/9300000175725335/',
      totalPriceMinor: 18800,
      availability: 'in_stock',
      observedAt: '2026-04-03T09:32:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '42177',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/mercedes-benz-g-500-professional-line-42177',
      totalPriceMinor: 24999,
      availability: 'in_stock',
      observedAt: '2026-04-03T09:36:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '10342',
      merchantId: 'bol',
      merchantProductUrl:
        'https://www.bol.com/nl/nl/p/lego-botanicals-pronkroze-boeket-bloemen-cadeau-voor-haar-10342/9300000206490401/',
      totalPriceMinor: 4499,
      availability: 'in_stock',
      observedAt: '2026-04-03T09:40:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '10342',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/pretty-pink-flower-bouquet-10342',
      totalPriceMinor: 5999,
      availability: 'in_stock',
      observedAt: '2026-04-03T09:44:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
  ];
