import {
  DUTCH_REGION_CODE,
  EURO_CURRENCY_CODE,
  NEW_OFFER_CONDITION,
  type PricingAvailability,
  type PricingCondition,
  type PricingCurrencyCode,
  type PricingRegionCode,
} from '@lego-platform/pricing/util';

export interface PricingObservationSeed {
  availability: PricingAvailability;
  condition: PricingCondition;
  currencyCode: PricingCurrencyCode;
  merchantId: string;
  merchantProductUrl: string;
  observedAt: string;
  regionCode: PricingRegionCode;
  setId: string;
  totalPriceMinor: number;
}

// Keep merchant product destinations curated per set.
// Do not synthesize product URLs from set ids or merchant naming patterns.
export const curatedDutchPricingObservationSeeds: readonly PricingObservationSeed[] =
  [
    {
      setId: '10316',
      merchantId: 'bol',
      merchantProductUrl:
        'https://www.bol.com/nl/nl/p/lego-10316-the-lord-of-the-rings-rivendell/9300000144104277/',
      totalPriceMinor: 46999,
      availability: 'in_stock',
      observedAt: '2026-03-31T09:00:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '10316',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/the-lord-of-the-rings-rivendell-10316',
      totalPriceMinor: 49999,
      availability: 'in_stock',
      observedAt: '2026-03-31T09:08:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '21348',
      merchantId: 'bol',
      merchantProductUrl:
        'https://www.bol.com/nl/nl/p/lego-ideas-dungeons-dragons-het-verhaal-van-de-rode-draak-21348/9300000175725314/',
      totalPriceMinor: 33499,
      availability: 'in_stock',
      observedAt: '2026-03-31T09:12:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '21348',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/dungeons-dragons-red-dragons-tale-21348',
      totalPriceMinor: 35999,
      availability: 'in_stock',
      observedAt: '2026-03-31T09:20:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '10305',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/lion-knights-castle-10305',
      totalPriceMinor: 38999,
      availability: 'in_stock',
      observedAt: '2026-03-31T09:40:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '10332',
      merchantId: 'bol',
      merchantProductUrl:
        'https://www.bol.com/nl/nl/p/lego-icons-middeleeuws-stadsplein-10332/9300000173010312/',
      totalPriceMinor: 21499,
      availability: 'in_stock',
      observedAt: '2026-03-31T09:44:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '10332',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/medieval-town-square-10332',
      totalPriceMinor: 22999,
      availability: 'in_stock',
      observedAt: '2026-03-31T09:52:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '10333',
      merchantId: 'bol',
      merchantProductUrl:
        'https://www.bol.com/nl/nl/p/lego-de-lord-of-the-rings-barad-majoor-10333/9300000180281419/',
      totalPriceMinor: 43999,
      availability: 'in_stock',
      observedAt: '2026-03-31T09:56:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '10333',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/the-lord-of-the-rings-barad-dur-10333',
      totalPriceMinor: 45999,
      availability: 'in_stock',
      observedAt: '2026-03-31T10:04:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '10294',
      merchantId: 'lego-nl',
      merchantProductUrl: 'https://www.lego.com/nl-nl/product/titanic-10294',
      totalPriceMinor: 65999,
      availability: 'in_stock',
      observedAt: '2026-03-31T10:32:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '21061',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/notre-dame-de-paris-21061',
      totalPriceMinor: 21999,
      availability: 'in_stock',
      observedAt: '2026-03-31T10:36:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '21333',
      merchantId: 'bol',
      merchantProductUrl:
        'https://www.bol.com/nl/nl/p/lego-ideas-vincent-van-gogh-sterrennacht-21333/9300000070995024/',
      totalPriceMinor: 14999,
      availability: 'in_stock',
      observedAt: '2026-03-31T10:08:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '21333',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/vincent-van-gogh-the-starry-night-21333',
      totalPriceMinor: 16999,
      availability: 'in_stock',
      observedAt: '2026-03-31T10:16:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '21349',
      merchantId: 'bol',
      merchantProductUrl:
        'https://www.bol.com/nl/nl/p/lego-ideas-zwart-witte-kat-21349/9300000173010346/',
      totalPriceMinor: 9499,
      availability: 'in_stock',
      observedAt: '2026-03-31T10:20:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '21349',
      merchantId: 'lego-nl',
      merchantProductUrl: 'https://www.lego.com/nl-nl/product/tuxedo-cat-21349',
      totalPriceMinor: 10999,
      availability: 'in_stock',
      observedAt: '2026-03-31T10:28:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '76178',
      merchantId: 'bol',
      merchantProductUrl:
        'https://www.bol.com/nl/nl/p/lego-spider-man-daily-bugle-76178/9300000040027340/',
      totalPriceMinor: 32999,
      availability: 'in_stock',
      observedAt: '2026-03-31T10:44:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '76178',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/daily-bugle-76178',
      totalPriceMinor: 33999,
      availability: 'in_stock',
      observedAt: '2026-03-31T10:48:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '75367',
      merchantId: 'bol',
      merchantProductUrl:
        'https://www.bol.com/nl/nl/p/lego-star-wars-venator-class-republic-attack-cruiser-75367/9300000161235312/',
      totalPriceMinor: 63999,
      availability: 'in_stock',
      observedAt: '2026-03-31T10:52:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '75367',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/venator-class-republic-attack-cruiser-75367',
      totalPriceMinor: 64999,
      availability: 'in_stock',
      observedAt: '2026-03-31T10:56:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '21350',
      merchantId: 'bol',
      merchantProductUrl:
        'https://www.bol.com/nl/nl/p/lego-21350-jaws-lego-ideas/9300000185934485/',
      totalPriceMinor: 15499,
      availability: 'in_stock',
      observedAt: '2026-03-31T11:00:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '21350',
      merchantId: 'lego-nl',
      merchantProductUrl: 'https://www.lego.com/nl-nl/product/jaws-21350',
      totalPriceMinor: 15999,
      availability: 'in_stock',
      observedAt: '2026-03-31T11:04:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '10317',
      merchantId: 'bol',
      merchantProductUrl:
        'https://www.bol.com/nl/nl/p/lego-10317-land-rover-classic-defender-90/9300000137836645/',
      totalPriceMinor: 22999,
      availability: 'in_stock',
      observedAt: '2026-03-31T11:08:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '10317',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/land-rover-classic-defender-90-10317',
      totalPriceMinor: 23999,
      availability: 'in_stock',
      observedAt: '2026-03-31T11:12:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '76269',
      merchantId: 'bol',
      merchantProductUrl:
        'https://www.bol.com/nl/nl/p/lego-avengers-toren-lego-marvel/9300000168131115/',
      totalPriceMinor: 46999,
      availability: 'in_stock',
      observedAt: '2026-03-31T09:24:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '76269',
      merchantId: 'intertoys',
      merchantProductUrl:
        'https://www.intertoys.nl/lego-marvel-avengers-toren-76269',
      totalPriceMinor: 47999,
      availability: 'limited',
      observedAt: '2026-03-31T09:30:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '76269',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/avengers-tower-76269',
      totalPriceMinor: 49999,
      availability: 'in_stock',
      observedAt: '2026-03-31T09:36:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '75355',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/x-wing-starfighter-75355',
      totalPriceMinor: 23999,
      availability: 'in_stock',
      observedAt: '2026-03-31T11:16:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '75397',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/jabbas-sail-barge-75397',
      totalPriceMinor: 49999,
      availability: 'in_stock',
      observedAt: '2026-03-31T11:20:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '76429',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/talking-sorting-hat-76429',
      totalPriceMinor: 9999,
      availability: 'in_stock',
      observedAt: '2026-03-31T11:24:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '76435',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/hogwarts-castle-the-great-hall-76435',
      totalPriceMinor: 19999,
      availability: 'in_stock',
      observedAt: '2026-03-31T11:28:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '76294',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/x-men-the-x-mansion-76294',
      totalPriceMinor: 32999,
      availability: 'in_stock',
      observedAt: '2026-03-31T11:32:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '10335',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/the-endurance-10335',
      totalPriceMinor: 26999,
      availability: 'in_stock',
      observedAt: '2026-03-31T11:36:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '10327',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/dune-atreides-royal-ornithopter-10327',
      totalPriceMinor: 16499,
      availability: 'in_stock',
      observedAt: '2026-03-31T11:40:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '42171',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/mercedes-amg-f1-w14-e-performance-42171',
      totalPriceMinor: 21999,
      availability: 'in_stock',
      observedAt: '2026-03-31T11:44:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '42172',
      merchantId: 'lego-nl',
      merchantProductUrl: 'https://www.lego.com/nl-nl/product/mclaren-p1-42172',
      totalPriceMinor: 44999,
      availability: 'in_stock',
      observedAt: '2026-03-31T11:48:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
    {
      setId: '10328',
      merchantId: 'lego-nl',
      merchantProductUrl:
        'https://www.lego.com/nl-nl/product/bouquet-of-roses-10328',
      totalPriceMinor: 5999,
      availability: 'in_stock',
      observedAt: '2026-03-31T11:52:00.000Z',
      regionCode: DUTCH_REGION_CODE,
      currencyCode: EURO_CURRENCY_CODE,
      condition: NEW_OFFER_CONDITION,
    },
  ];
