import type { PricePanelSnapshot } from '@lego-platform/pricing/util';

// Generated by apps/commerce-sync. Do not edit by hand.
export const pricePanelSnapshots: readonly PricePanelSnapshot[] = [
  {
    "setId": "10316",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "headlinePriceMinor": 48999,
    "lowestAvailabilityLabel": "In stock",
    "lowestMerchantId": "bol",
    "lowestMerchantName": "bol",
    "merchantCount": 3,
    "observedAt": "2026-03-29T09:00:00.000Z",
    "referencePriceMinor": 49999,
    "deltaMinor": -1000
  },
  {
    "setId": "21348",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "headlinePriceMinor": 34999,
    "lowestAvailabilityLabel": "In stock",
    "lowestMerchantId": "bol",
    "lowestMerchantName": "bol",
    "merchantCount": 3,
    "observedAt": "2026-03-29T09:15:00.000Z",
    "referencePriceMinor": 35999,
    "deltaMinor": -1000
  },
  {
    "setId": "76269",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "headlinePriceMinor": 47999,
    "lowestAvailabilityLabel": "In stock",
    "lowestMerchantId": "bol",
    "lowestMerchantName": "bol",
    "merchantCount": 3,
    "observedAt": "2026-03-29T09:30:00.000Z",
    "referencePriceMinor": 49999,
    "deltaMinor": -2000
  }
];
