import type { PricingSyncManifest } from '@lego-platform/pricing/util';

// Generated by apps/commerce-sync. Do not edit by hand.
const pricingSyncManifestPayload = String.raw`{
  "source": "supabase-commerce-refresh",
  "generatedAt": "2026-06-16T11:19:18.511Z",
  "observationCount": 8093,
  "setCount": 1352,
  "notes": "Generated from Supabase-managed commerce seeds and the latest verified merchant refresh state."
}`;

export const pricingSyncManifest: PricingSyncManifest = JSON.parse(
  pricingSyncManifestPayload,
) as PricingSyncManifest;
