import type { PricingObservation } from '@lego-platform/pricing/util';

// Generated by apps/commerce-sync. Do not edit by hand.
const pricingObservationsPayload = String.raw`[
  {
    "setId": "10294",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 67999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:53.645Z"
  },
  {
    "setId": "10305",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 39999,
    "availability": "out_of_stock",
    "observedAt": "2026-04-15T15:12:56.594Z"
  },
  {
    "setId": "10305",
    "merchantId": "amazon-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 60900,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:13:22.182Z"
  },
  {
    "setId": "10316",
    "merchantId": "amazon-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 48246,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:13:24.097Z"
  },
  {
    "setId": "10316",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 49999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:58.270Z"
  },
  {
    "setId": "10317",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 23999,
    "availability": "out_of_stock",
    "observedAt": "2026-04-15T15:12:46.653Z"
  },
  {
    "setId": "10317",
    "merchantId": "amazon-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 29126,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:13:16.769Z"
  },
  {
    "setId": "10327",
    "merchantId": "amazon-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 11999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:00.133Z"
  },
  {
    "setId": "10327",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 13999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:11:56.853Z"
  },
  {
    "setId": "10327",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 14999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:11:56.468Z"
  },
  {
    "setId": "10327",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 16499,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:36.635Z"
  },
  {
    "setId": "10328",
    "merchantId": "amazon-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 4599,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:13:07.795Z"
  },
  {
    "setId": "10328",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 4999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:07.015Z"
  },
  {
    "setId": "10328",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 5199,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:07.308Z"
  },
  {
    "setId": "10328",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 5999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:32.978Z"
  },
  {
    "setId": "10332",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 22999,
    "availability": "out_of_stock",
    "observedAt": "2026-04-15T15:12:55.537Z"
  },
  {
    "setId": "10332",
    "merchantId": "amazon-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 30185,
    "availability": "in_stock",
    "observedAt": "2026-04-14T19:59:10.632Z"
  },
  {
    "setId": "10333",
    "merchantId": "amazon-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 41958,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:13:26.503Z"
  },
  {
    "setId": "10333",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 45999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:54.599Z"
  },
  {
    "setId": "10335",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 26999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:37.400Z"
  },
  {
    "setId": "10335",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 29700,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:11:49.373Z"
  },
  {
    "setId": "10342",
    "merchantId": "amazon-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 4399,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:13:00.811Z"
  },
  {
    "setId": "10342",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 4399,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:16.385Z"
  },
  {
    "setId": "10342",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 5199,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:06.165Z"
  },
  {
    "setId": "10342",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 5999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:13:19.021Z"
  },
  {
    "setId": "10342",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 5999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:05.880Z"
  },
  {
    "setId": "10354",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 25999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:11:47.800Z"
  },
  {
    "setId": "10354",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 26999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:13:29.759Z"
  },
  {
    "setId": "10354",
    "merchantId": "amazon-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 38499,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:13:03.507Z"
  },
  {
    "setId": "21061",
    "merchantId": "amazon-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 17240,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:24.954Z"
  },
  {
    "setId": "21061",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 19999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:11:59.166Z"
  },
  {
    "setId": "21061",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 22999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:26.726Z"
  },
  {
    "setId": "21061",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 22999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:24.491Z"
  },
  {
    "setId": "21333",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 16999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:52.410Z"
  },
  {
    "setId": "21348",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 30299,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:11:42.028Z"
  },
  {
    "setId": "21348",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 35999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:57.457Z"
  },
  {
    "setId": "21348",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 35999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:11:41.616Z"
  },
  {
    "setId": "21349",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 9999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:51.393Z"
  },
  {
    "setId": "21350",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 13499,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:11:37.425Z"
  },
  {
    "setId": "21350",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 14999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:48.085Z"
  },
  {
    "setId": "42171",
    "merchantId": "amazon-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 15171,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:10:44.009Z"
  },
  {
    "setId": "42171",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 15999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:10:42.723Z"
  },
  {
    "setId": "42171",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 15999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:10:41.532Z"
  },
  {
    "setId": "42171",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 17999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:10:41.144Z"
  },
  {
    "setId": "42171",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 21999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:35.605Z"
  },
  {
    "setId": "42172",
    "merchantId": "amazon-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 31999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:13:10.192Z"
  },
  {
    "setId": "42172",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 32499,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:10:46.453Z"
  },
  {
    "setId": "42172",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 37999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:10:46.074Z"
  },
  {
    "setId": "42172",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 44999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:34.084Z"
  },
  {
    "setId": "42177",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 18499,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:10:35.557Z"
  },
  {
    "setId": "42177",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 19999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:10:35.052Z"
  },
  {
    "setId": "42177",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 24999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:13:28.700Z"
  },
  {
    "setId": "75313",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 84999,
    "availability": "out_of_stock",
    "observedAt": "2026-04-15T15:11:17.318Z"
  },
  {
    "setId": "75313",
    "merchantId": "amazon-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 132900,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:11:20.463Z"
  },
  {
    "setId": "75355",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 23999,
    "availability": "out_of_stock",
    "observedAt": "2026-04-15T15:12:44.030Z"
  },
  {
    "setId": "75355",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 23999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:10:49.807Z"
  },
  {
    "setId": "75367",
    "merchantId": "amazon-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 4725,
    "availability": "unknown",
    "observedAt": "2026-04-14T19:22:32.339Z"
  },
  {
    "setId": "75367",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 48999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:10:54.667Z"
  },
  {
    "setId": "75367",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 64999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:48.901Z"
  },
  {
    "setId": "75367",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 64999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:10:54.094Z"
  },
  {
    "setId": "75397",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 37499,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:10:59.492Z"
  },
  {
    "setId": "75397",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 49999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:41.730Z"
  },
  {
    "setId": "75398",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 10499,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:11:12.317Z"
  },
  {
    "setId": "75398",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 13999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:30.788Z"
  },
  {
    "setId": "75398",
    "merchantId": "amazon-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 17998,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:11:15.078Z"
  },
  {
    "setId": "76178",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 34999,
    "availability": "out_of_stock",
    "observedAt": "2026-04-15T15:12:50.338Z"
  },
  {
    "setId": "76178",
    "merchantId": "amazon-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 43000,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:11:09.538Z"
  },
  {
    "setId": "76269",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 42999,
    "availability": "out_of_stock",
    "observedAt": "2026-04-15T15:12:59.849Z"
  },
  {
    "setId": "76269",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 49900,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:11:27.805Z"
  },
  {
    "setId": "76269",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 49999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:45.654Z"
  },
  {
    "setId": "76294",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 27999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:11:03.794Z"
  },
  {
    "setId": "76294",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 32999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:38.320Z"
  },
  {
    "setId": "76313",
    "merchantId": "amazon-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 8153,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:11:25.183Z"
  },
  {
    "setId": "76313",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 8499,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:11:22.838Z"
  },
  {
    "setId": "76313",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 8499,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:11:22.461Z"
  },
  {
    "setId": "76313",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 8599,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:11:23.878Z"
  },
  {
    "setId": "76313",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 9999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:27.831Z"
  },
  {
    "setId": "76419",
    "merchantId": "amazon-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 13129,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:21.690Z"
  },
  {
    "setId": "76419",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 14499,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:08.769Z"
  },
  {
    "setId": "76419",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 16999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:20.757Z"
  },
  {
    "setId": "76419",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 16999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:08.504Z"
  },
  {
    "setId": "76429",
    "merchantId": "amazon-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 7490,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:13:14.485Z"
  },
  {
    "setId": "76429",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 8299,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:02.318Z"
  },
  {
    "setId": "76429",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 8499,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:03.006Z"
  },
  {
    "setId": "76429",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 9999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:40.828Z"
  },
  {
    "setId": "76435",
    "merchantId": "amazon-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 14932,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:13:12.383Z"
  },
  {
    "setId": "76435",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 17999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:09.899Z"
  },
  {
    "setId": "76435",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 19999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:39.187Z"
  },
  {
    "setId": "76435",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 19999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:09.629Z"
  },
  {
    "setId": "76453",
    "merchantId": "amazon-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 11999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:13:05.647Z"
  },
  {
    "setId": "76453",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 12999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:12.133Z"
  },
  {
    "setId": "76453",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 12999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:13.640Z"
  },
  {
    "setId": "76453",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 14999,
    "availability": "in_stock",
    "observedAt": "2026-04-15T15:12:29.759Z"
  }
]`;

export const pricingObservations: readonly PricingObservation[] = JSON.parse(
  pricingObservationsPayload,
) as readonly PricingObservation[];
