import type { PricingObservation } from '@lego-platform/pricing/util';

// Generated by apps/commerce-sync. Do not edit by hand.
export const pricingObservations: readonly PricingObservation[] = [
  {
    "setId": "10294",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 65999,
    "availability": "in_stock",
    "observedAt": "2026-03-31T10:32:00.000Z"
  },
  {
    "setId": "10305",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 38999,
    "availability": "in_stock",
    "observedAt": "2026-03-31T09:40:00.000Z"
  },
  {
    "setId": "10316",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 46999,
    "availability": "in_stock",
    "observedAt": "2026-03-31T09:00:00.000Z"
  },
  {
    "setId": "10316",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 49999,
    "availability": "in_stock",
    "observedAt": "2026-03-31T09:08:00.000Z"
  },
  {
    "setId": "10317",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 22999,
    "availability": "in_stock",
    "observedAt": "2026-03-31T11:08:00.000Z"
  },
  {
    "setId": "10317",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 23999,
    "availability": "in_stock",
    "observedAt": "2026-03-31T11:12:00.000Z"
  },
  {
    "setId": "10327",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 16499,
    "availability": "in_stock",
    "observedAt": "2026-03-31T11:40:00.000Z"
  },
  {
    "setId": "10328",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 5999,
    "availability": "in_stock",
    "observedAt": "2026-03-31T11:52:00.000Z"
  },
  {
    "setId": "10332",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 21499,
    "availability": "in_stock",
    "observedAt": "2026-03-31T09:44:00.000Z"
  },
  {
    "setId": "10332",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 22999,
    "availability": "in_stock",
    "observedAt": "2026-03-31T09:52:00.000Z"
  },
  {
    "setId": "10333",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 43999,
    "availability": "in_stock",
    "observedAt": "2026-03-31T09:56:00.000Z"
  },
  {
    "setId": "10333",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 45999,
    "availability": "in_stock",
    "observedAt": "2026-03-31T10:04:00.000Z"
  },
  {
    "setId": "10335",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 26999,
    "availability": "in_stock",
    "observedAt": "2026-03-31T11:36:00.000Z"
  },
  {
    "setId": "21061",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 21999,
    "availability": "in_stock",
    "observedAt": "2026-03-31T10:36:00.000Z"
  },
  {
    "setId": "21333",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 14999,
    "availability": "in_stock",
    "observedAt": "2026-03-31T10:08:00.000Z"
  },
  {
    "setId": "21333",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 16999,
    "availability": "in_stock",
    "observedAt": "2026-03-31T10:16:00.000Z"
  },
  {
    "setId": "21348",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 33499,
    "availability": "in_stock",
    "observedAt": "2026-03-31T09:12:00.000Z"
  },
  {
    "setId": "21348",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 35999,
    "availability": "in_stock",
    "observedAt": "2026-03-31T09:20:00.000Z"
  },
  {
    "setId": "21349",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 9499,
    "availability": "in_stock",
    "observedAt": "2026-03-31T10:20:00.000Z"
  },
  {
    "setId": "21349",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 10999,
    "availability": "in_stock",
    "observedAt": "2026-03-31T10:28:00.000Z"
  },
  {
    "setId": "21350",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 15499,
    "availability": "in_stock",
    "observedAt": "2026-03-31T11:00:00.000Z"
  },
  {
    "setId": "21350",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 15999,
    "availability": "in_stock",
    "observedAt": "2026-03-31T11:04:00.000Z"
  },
  {
    "setId": "42171",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 21999,
    "availability": "in_stock",
    "observedAt": "2026-03-31T11:44:00.000Z"
  },
  {
    "setId": "42172",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 44999,
    "availability": "in_stock",
    "observedAt": "2026-03-31T11:48:00.000Z"
  },
  {
    "setId": "75355",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 23999,
    "availability": "in_stock",
    "observedAt": "2026-03-31T11:16:00.000Z"
  },
  {
    "setId": "75367",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 63999,
    "availability": "in_stock",
    "observedAt": "2026-03-31T10:52:00.000Z"
  },
  {
    "setId": "75367",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 64999,
    "availability": "in_stock",
    "observedAt": "2026-03-31T10:56:00.000Z"
  },
  {
    "setId": "75397",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 49999,
    "availability": "in_stock",
    "observedAt": "2026-03-31T11:20:00.000Z"
  },
  {
    "setId": "76178",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 32999,
    "availability": "in_stock",
    "observedAt": "2026-03-31T10:44:00.000Z"
  },
  {
    "setId": "76178",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 33999,
    "availability": "in_stock",
    "observedAt": "2026-03-31T10:48:00.000Z"
  },
  {
    "setId": "76269",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 46999,
    "availability": "in_stock",
    "observedAt": "2026-03-31T09:24:00.000Z"
  },
  {
    "setId": "76269",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 47999,
    "availability": "limited",
    "observedAt": "2026-03-31T09:30:00.000Z"
  },
  {
    "setId": "76269",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 49999,
    "availability": "in_stock",
    "observedAt": "2026-03-31T09:36:00.000Z"
  },
  {
    "setId": "76294",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 32999,
    "availability": "in_stock",
    "observedAt": "2026-03-31T11:32:00.000Z"
  },
  {
    "setId": "76429",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 9999,
    "availability": "in_stock",
    "observedAt": "2026-03-31T11:24:00.000Z"
  },
  {
    "setId": "76435",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 19999,
    "availability": "in_stock",
    "observedAt": "2026-03-31T11:28:00.000Z"
  }
];
