import type { PricingSyncManifest } from '@lego-platform/pricing/util';

// Generated by apps/commerce-sync. Do not edit by hand.
const pricingSyncManifestPayload = String.raw`{
  "source": "supabase-commerce-refresh",
  "generatedAt": "2026-05-05T13:30:30.204Z",
  "observationCount": 370,
  "setCount": 212,
  "notes": "Generated from Supabase-managed commerce seeds and the latest verified merchant refresh state."
}`;

export const pricingSyncManifest: PricingSyncManifest = JSON.parse(
  pricingSyncManifestPayload,
) as PricingSyncManifest;
