import type { PricingObservation } from '@lego-platform/pricing/util';

// Generated by apps/commerce-sync. Do not edit by hand.
const pricingObservationsPayload = String.raw`[
  {
    "setId": "10280",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 4598,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:11.030Z"
  },
  {
    "setId": "10280",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 4995,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:14.314Z"
  },
  {
    "setId": "10280",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 4999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:15.010Z"
  },
  {
    "setId": "10280",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 5199,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:11.938Z"
  },
  {
    "setId": "10280",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 5999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:12.788Z"
  },
  {
    "setId": "10294",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 67999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:51.036Z"
  },
  {
    "setId": "10294",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 79125,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:48.440Z"
  },
  {
    "setId": "10300",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 16900,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:06.348Z"
  },
  {
    "setId": "10300",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 16900,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:31:53.468Z"
  },
  {
    "setId": "10300",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 19999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:31:52.474Z"
  },
  {
    "setId": "10305",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 39999,
    "availability": "out_of_stock",
    "observedAt": "2026-04-19T17:24:53.041Z"
  },
  {
    "setId": "10305",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 48900,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:41.253Z"
  },
  {
    "setId": "10311",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 3799,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:07.108Z"
  },
  {
    "setId": "10311",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 4195,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:10.110Z"
  },
  {
    "setId": "10311",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 4199,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:10.780Z"
  },
  {
    "setId": "10311",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 4499,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:07.923Z"
  },
  {
    "setId": "10311",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 4999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:08.716Z"
  },
  {
    "setId": "10316",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 48246,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:43.829Z"
  },
  {
    "setId": "10316",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 49995,
    "availability": "out_of_stock",
    "observedAt": "2026-04-19T18:54:37.194Z"
  },
  {
    "setId": "10316",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 49999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:44.834Z"
  },
  {
    "setId": "10317",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 23900,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:35.275Z"
  },
  {
    "setId": "10317",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 23999,
    "availability": "out_of_stock",
    "observedAt": "2026-04-19T17:25:02.312Z"
  },
  {
    "setId": "10317",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 27995,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:40.252Z"
  },
  {
    "setId": "10320",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 21499,
    "availability": "out_of_stock",
    "observedAt": "2026-04-19T17:24:49.334Z"
  },
  {
    "setId": "10320",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 24500,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:05.391Z"
  },
  {
    "setId": "10327",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 11999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:37.897Z"
  },
  {
    "setId": "10327",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 13500,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:35.789Z"
  },
  {
    "setId": "10327",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 13999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:39.279Z"
  },
  {
    "setId": "10327",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 14999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:40.044Z"
  },
  {
    "setId": "10327",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 16499,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:08.337Z"
  },
  {
    "setId": "10328",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 4599,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:21.694Z"
  },
  {
    "setId": "10328",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 4995,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:34:12.364Z"
  },
  {
    "setId": "10328",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 4999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:32.578Z"
  },
  {
    "setId": "10328",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 5199,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:31.092Z"
  },
  {
    "setId": "10328",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 5999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:12.148Z"
  },
  {
    "setId": "10332",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 22999,
    "availability": "out_of_stock",
    "observedAt": "2026-04-19T17:24:59.689Z"
  },
  {
    "setId": "10332",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 25499,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:42.445Z"
  },
  {
    "setId": "10333",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 45999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:50.213Z"
  },
  {
    "setId": "10333",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 50600,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:46.205Z"
  },
  {
    "setId": "10335",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 26999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:07.507Z"
  },
  {
    "setId": "10335",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 29700,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:45.054Z"
  },
  {
    "setId": "10342",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 4399,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:22.951Z"
  },
  {
    "setId": "10342",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 4900,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:34:12.812Z"
  },
  {
    "setId": "10342",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 5199,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:32.695Z"
  },
  {
    "setId": "10342",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 5999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:42.841Z"
  },
  {
    "setId": "10342",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 5999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:33.501Z"
  },
  {
    "setId": "10354",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 24900,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:31:54.254Z"
  },
  {
    "setId": "10354",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 25899,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:47.717Z"
  },
  {
    "setId": "10354",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 25999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:47.539Z"
  },
  {
    "setId": "10354",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 26999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:37.142Z"
  },
  {
    "setId": "21061",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 17240,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:19.825Z"
  },
  {
    "setId": "21061",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 18400,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:34:11.924Z"
  },
  {
    "setId": "21061",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 19999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:36.206Z"
  },
  {
    "setId": "21061",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 22999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:17.002Z"
  },
  {
    "setId": "21061",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 22999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:18.003Z"
  },
  {
    "setId": "21333",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 15990,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:54.157Z"
  },
  {
    "setId": "21333",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 16999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:52.865Z"
  },
  {
    "setId": "21338",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 17999,
    "availability": "out_of_stock",
    "observedAt": "2026-04-19T17:24:48.161Z"
  },
  {
    "setId": "21338",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 22600,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:31:59.147Z"
  },
  {
    "setId": "21348",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 30299,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:49.366Z"
  },
  {
    "setId": "21348",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 32500,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:34:21.345Z"
  },
  {
    "setId": "21348",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 35999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:46.312Z"
  },
  {
    "setId": "21348",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 35999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:50.353Z"
  },
  {
    "setId": "21349",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 8999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:52.953Z"
  },
  {
    "setId": "21349",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 9999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:53.878Z"
  },
  {
    "setId": "21350",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 13499,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:51.268Z"
  },
  {
    "setId": "21350",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 14999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:56.278Z"
  },
  {
    "setId": "21350",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 15000,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:50.478Z"
  },
  {
    "setId": "31208",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 7999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:21.741Z"
  },
  {
    "setId": "31208",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 7999,
    "availability": "out_of_stock",
    "observedAt": "2026-04-19T18:23:01.759Z"
  },
  {
    "setId": "31208",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 7999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:18.235Z"
  },
  {
    "setId": "31208",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 8295,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:18.409Z"
  },
  {
    "setId": "31208",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 9999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:19.255Z"
  },
  {
    "setId": "42143",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 32499,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:03.034Z"
  },
  {
    "setId": "42143",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 32499,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:01.990Z"
  },
  {
    "setId": "42143",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 35900,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:00.367Z"
  },
  {
    "setId": "42143",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 37999,
    "availability": "out_of_stock",
    "observedAt": "2026-04-19T09:32:00.059Z"
  },
  {
    "setId": "42143",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 44999,
    "availability": "unknown",
    "observedAt": "2026-04-19T09:32:00.940Z"
  },
  {
    "setId": "42171",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 15999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:34:07.985Z"
  },
  {
    "setId": "42171",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 15999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:34:08.864Z"
  },
  {
    "setId": "42171",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 17900,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:34:21.055Z"
  },
  {
    "setId": "42171",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 17999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:34:09.750Z"
  },
  {
    "setId": "42171",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 21999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:09.577Z"
  },
  {
    "setId": "42172",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 31999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:34:05.754Z"
  },
  {
    "setId": "42172",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 32499,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:34:06.592Z"
  },
  {
    "setId": "42172",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 35900,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:34:20.664Z"
  },
  {
    "setId": "42172",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 37999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:34:07.751Z"
  },
  {
    "setId": "42172",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 44999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:10.697Z"
  },
  {
    "setId": "42177",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 18499,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:34:10.792Z"
  },
  {
    "setId": "42177",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 18900,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:34:09.874Z"
  },
  {
    "setId": "42177",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 19999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:34:11.801Z"
  },
  {
    "setId": "42177",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 20900,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:34:20.214Z"
  },
  {
    "setId": "42177",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 24999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:41.505Z"
  },
  {
    "setId": "43222",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 39999,
    "availability": "out_of_stock",
    "observedAt": "2026-04-19T17:24:51.259Z"
  },
  {
    "setId": "43222",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 71899,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:17.537Z"
  },
  {
    "setId": "43269",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 10900,
    "availability": "in_stock",
    "observedAt": "2026-04-19T20:21:51.840Z"
  },
  {
    "setId": "43269",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 11500,
    "availability": "in_stock",
    "observedAt": "2026-04-19T20:21:54.815Z"
  },
  {
    "setId": "43269",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 11999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T20:21:52.506Z"
  },
  {
    "setId": "43269",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 13999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T20:21:53.665Z"
  },
  {
    "setId": "72037",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 11900,
    "availability": "in_stock",
    "observedAt": "2026-04-19T17:57:52.628Z"
  },
  {
    "setId": "72037",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 11999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T17:57:54.688Z"
  },
  {
    "setId": "72037",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 13900,
    "availability": "in_stock",
    "observedAt": "2026-04-19T17:57:52.339Z"
  },
  {
    "setId": "72037",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 13999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:34:13.396Z"
  },
  {
    "setId": "72037",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 16999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T17:57:49.089Z"
  },
  {
    "setId": "72050",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 15500,
    "availability": "out_of_stock",
    "observedAt": "2026-04-19T17:57:51.505Z"
  },
  {
    "setId": "72050",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 17999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T17:57:55.638Z"
  },
  {
    "setId": "75192",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 63799,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:28.710Z"
  },
  {
    "setId": "75192",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 63799,
    "availability": "in_stock",
    "observedAt": "2026-04-19T17:15:18.782Z"
  },
  {
    "setId": "75192",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 67500,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:32.871Z"
  },
  {
    "setId": "75192",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 84999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T18:14:45.876Z"
  },
  {
    "setId": "75313",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 84999,
    "availability": "out_of_stock",
    "observedAt": "2026-04-19T17:25:04.734Z"
  },
  {
    "setId": "75313",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 104995,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:58.301Z"
  },
  {
    "setId": "75355",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 22900,
    "availability": "in_stock",
    "observedAt": "2026-04-19T10:27:19.036Z"
  },
  {
    "setId": "75355",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 23249,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:22.889Z"
  },
  {
    "setId": "75355",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 23999,
    "availability": "out_of_stock",
    "observedAt": "2026-04-19T17:25:06.934Z"
  },
  {
    "setId": "75355",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 23999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:22.682Z"
  },
  {
    "setId": "75367",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 48999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:25.550Z"
  },
  {
    "setId": "75367",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 54900,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:26.351Z"
  },
  {
    "setId": "75367",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 59900,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:28.331Z"
  },
  {
    "setId": "75367",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 64999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:27.018Z"
  },
  {
    "setId": "75367",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 64999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:25.423Z"
  },
  {
    "setId": "75397",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 37499,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:34:05.019Z"
  },
  {
    "setId": "75397",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 42500,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:34:04.110Z"
  },
  {
    "setId": "75397",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 46900,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:31:51.242Z"
  },
  {
    "setId": "75397",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 49999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:00.507Z"
  },
  {
    "setId": "75398",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 10499,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:59.131Z"
  },
  {
    "setId": "75398",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 10499,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:34:00.215Z"
  },
  {
    "setId": "75398",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 11900,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:31:51.523Z"
  },
  {
    "setId": "75398",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 13999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:13.230Z"
  },
  {
    "setId": "75440",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 4999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:31.149Z"
  },
  {
    "setId": "75440",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 5198,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:32.043Z"
  },
  {
    "setId": "75440",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 5495,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:34.668Z"
  },
  {
    "setId": "75440",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 6499,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:30.031Z"
  },
  {
    "setId": "76178",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 34999,
    "availability": "out_of_stock",
    "observedAt": "2026-04-19T17:25:03.683Z"
  },
  {
    "setId": "76178",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 45095,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:34:01.368Z"
  },
  {
    "setId": "76269",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 42999,
    "availability": "out_of_stock",
    "observedAt": "2026-04-19T18:23:32.363Z"
  },
  {
    "setId": "76269",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 49900,
    "availability": "in_stock",
    "observedAt": "2026-04-19T10:27:18.497Z"
  },
  {
    "setId": "76269",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 49900,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:56.451Z"
  },
  {
    "setId": "76269",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 49999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T10:28:56.377Z"
  },
  {
    "setId": "76269",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 54975,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:55.449Z"
  },
  {
    "setId": "76294",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 27999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T10:28:07.062Z"
  },
  {
    "setId": "76294",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 28000,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:34:02.367Z"
  },
  {
    "setId": "76294",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 32999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T10:28:54.814Z"
  },
  {
    "setId": "76313",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 7668,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:56.634Z"
  },
  {
    "setId": "76313",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 8195,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:31:52.198Z"
  },
  {
    "setId": "76313",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 8499,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:57.260Z"
  },
  {
    "setId": "76313",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 8499,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:58.175Z"
  },
  {
    "setId": "76313",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 9999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:16.291Z"
  },
  {
    "setId": "76330",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 6300,
    "availability": "in_stock",
    "observedAt": "2026-04-19T20:21:55.362Z"
  },
  {
    "setId": "76330",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 6500,
    "availability": "in_stock",
    "observedAt": "2026-04-19T20:21:55.821Z"
  },
  {
    "setId": "76330",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 6695,
    "availability": "in_stock",
    "observedAt": "2026-04-19T20:21:57.546Z"
  },
  {
    "setId": "76330",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 7999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T20:21:56.528Z"
  },
  {
    "setId": "76417",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 42999,
    "availability": "unknown",
    "observedAt": "2026-04-19T10:29:02.430Z"
  },
  {
    "setId": "76417",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 48900,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:31:56.916Z"
  },
  {
    "setId": "76419",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 13129,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:24.327Z"
  },
  {
    "setId": "76419",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 13900,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:34:13.097Z"
  },
  {
    "setId": "76419",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 14499,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:30.016Z"
  },
  {
    "setId": "76419",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 16999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:18.275Z"
  },
  {
    "setId": "76419",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 16999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:30.894Z"
  },
  {
    "setId": "76429",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 7490,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:33.632Z"
  },
  {
    "setId": "76429",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 8295,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:36.073Z"
  },
  {
    "setId": "76429",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 8299,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:36.084Z"
  },
  {
    "setId": "76429",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 8499,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:34.536Z"
  },
  {
    "setId": "76429",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 9999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:01.884Z"
  },
  {
    "setId": "76435",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 15200,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:25.520Z"
  },
  {
    "setId": "76435",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 16900,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:36.822Z"
  },
  {
    "setId": "76435",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 17999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:29.149Z"
  },
  {
    "setId": "76435",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 19999,
    "availability": "unknown",
    "observedAt": "2026-04-19T09:33:02.682Z"
  },
  {
    "setId": "76435",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 19999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:29.881Z"
  },
  {
    "setId": "76437",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 19999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:34:17.045Z"
  },
  {
    "setId": "76437",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 23900,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:34:16.755Z"
  },
  {
    "setId": "76437",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 25000,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:34:15.915Z"
  },
  {
    "setId": "76437",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 25999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:34:17.907Z"
  },
  {
    "setId": "76453",
    "merchantId": "bol",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 11999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:28.261Z"
  },
  {
    "setId": "76453",
    "merchantId": "misterbricks",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 12495,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:32:36.441Z"
  },
  {
    "setId": "76453",
    "merchantId": "intertoys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 12999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:27.152Z"
  },
  {
    "setId": "76453",
    "merchantId": "top1toys",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 12999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:26.879Z"
  },
  {
    "setId": "76453",
    "merchantId": "lego-nl",
    "regionCode": "NL",
    "currencyCode": "EUR",
    "condition": "new",
    "totalPriceMinor": 14999,
    "availability": "in_stock",
    "observedAt": "2026-04-19T09:33:15.210Z"
  }
]`;

export const pricingObservations: readonly PricingObservation[] = JSON.parse(
  pricingObservationsPayload,
) as readonly PricingObservation[];
