import type { AffiliateSyncManifest } from '@lego-platform/affiliate/util';

// Generated by apps/commerce-sync. Do not edit by hand.
const affiliateSyncManifestPayload = String.raw`{
  "source": "supabase-commerce-refresh",
  "generatedAt": "2026-04-20T08:54:06.676Z",
  "offerCount": 219,
  "setCount": 61,
  "merchantCount": 6,
  "notes": "Generated from Supabase-managed commerce seeds and the latest verified merchant refresh state."
}`;

export const affiliateSyncManifest: AffiliateSyncManifest = JSON.parse(
  affiliateSyncManifestPayload,
) as AffiliateSyncManifest;
