import type { AffiliateSyncManifest } from '@lego-platform/affiliate/util';

// Generated by apps/commerce-sync. Do not edit by hand.
const affiliateSyncManifestPayload = String.raw`{
  "source": "supabase-commerce-refresh",
  "generatedAt": "2026-04-30T08:29:36.872Z",
  "offerCount": 674,
  "setCount": 220,
  "merchantCount": 9,
  "notes": "Generated from Supabase-managed commerce seeds and the latest verified merchant refresh state."
}`;

export const affiliateSyncManifest: AffiliateSyncManifest = JSON.parse(
  affiliateSyncManifestPayload,
) as AffiliateSyncManifest;
