import type {
  AppCurrencyCode,
  AppMarketCode,
} from '@lego-platform/shared/config';

export const DUTCH_AFFILIATE_REGION_CODE = 'NL';
export const EURO_AFFILIATE_CURRENCY_CODE = 'EUR';
export const NEW_AFFILIATE_OFFER_CONDITION = 'new';

export type AffiliateRegionCode = AppMarketCode;
export type AffiliateCurrencyCode = AppCurrencyCode;
export type AffiliateCondition = typeof NEW_AFFILIATE_OFFER_CONDITION;

export interface AffiliateMerchantConfig {
  ctaLabel: string;
  currencyCode: AffiliateCurrencyCode;
  disclosureCopy: string;
  displayName: string;
  displayRank: number;
  enabled: boolean;
  merchantId: string;
  perks?: string;
  regionCode: AffiliateRegionCode;
  urlHost: string;
}

export interface AffiliateOfferSnapshot {
  availabilityLabel: string;
  condition: AffiliateCondition;
  currencyCode: AffiliateCurrencyCode;
  ctaLabel: string;
  disclosureCopy: string;
  displayRank: number;
  merchantId: string;
  merchantName: string;
  observedAt: string;
  outboundUrl: string;
  perks?: string;
  regionCode: AffiliateRegionCode;
  setId: string;
  totalPriceMinor: number;
}

export interface AffiliateSyncManifest {
  generatedAt: string;
  merchantCount: number;
  notes?: string;
  offerCount: number;
  setCount: number;
  source: string;
}

export function sortAffiliateOffers(
  affiliateOffers: readonly AffiliateOfferSnapshot[],
): AffiliateOfferSnapshot[] {
  return [...affiliateOffers].sort(
    (left, right) =>
      left.totalPriceMinor - right.totalPriceMinor ||
      left.displayRank - right.displayRank ||
      left.merchantName.localeCompare(right.merchantName),
  );
}

function renderAffiliateGeneratedModule<
  T extends AffiliateSyncManifest | readonly AffiliateOfferSnapshot[],
>({
  exportName,
  importNames,
  typeAnnotation,
  payload,
}: {
  exportName: 'affiliateOfferSnapshots' | 'affiliateSyncManifest';
  importNames: string[];
  typeAnnotation: string;
  payload: T;
}): string {
  return `import type { ${importNames.join(', ')} } from '@lego-platform/affiliate/util';

// Generated by apps/commerce-sync. Do not edit by hand.
export const ${exportName}: ${typeAnnotation} = ${JSON.stringify(payload, null, 2)};
`;
}

export function renderAffiliateOfferSnapshotsModule(
  affiliateOfferSnapshots: readonly AffiliateOfferSnapshot[],
): string {
  return renderAffiliateGeneratedModule({
    exportName: 'affiliateOfferSnapshots',
    importNames: ['AffiliateOfferSnapshot'],
    typeAnnotation: 'readonly AffiliateOfferSnapshot[]',
    payload: affiliateOfferSnapshots,
  });
}

export function renderAffiliateSyncManifestModule(
  affiliateSyncManifest: AffiliateSyncManifest,
): string {
  return renderAffiliateGeneratedModule({
    exportName: 'affiliateSyncManifest',
    importNames: ['AffiliateSyncManifest'],
    typeAnnotation: 'AffiliateSyncManifest',
    payload: affiliateSyncManifest,
  });
}
