import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import type { CatalogSnapshot, CatalogSyncManifest } from '@lego-platform/catalog/util';

const GENERATED_SNAPSHOT_PATH =
  'libs/catalog/data-access/src/lib/catalog-snapshot.generated.ts';
const GENERATED_MANIFEST_PATH =
  'libs/catalog/data-access/src/lib/catalog-sync-manifest.generated.ts';

function renderGeneratedModule<T extends CatalogSnapshot | CatalogSyncManifest>(
  exportName: 'catalogSnapshot' | 'catalogSyncManifest',
  importName: 'CatalogSnapshot' | 'CatalogSyncManifest',
  payload: T,
): string {
  return `import type { ${importName} } from '@lego-platform/catalog/util';

// Generated by apps/catalog-sync. Do not edit by hand.
export const ${exportName}: ${importName} = ${JSON.stringify(payload, null, 2)};
`;
}

export function renderCatalogSnapshotModule(
  catalogSnapshot: CatalogSnapshot,
): string {
  return renderGeneratedModule(
    'catalogSnapshot',
    'CatalogSnapshot',
    catalogSnapshot,
  );
}

export function renderCatalogSyncManifestModule(
  catalogSyncManifest: CatalogSyncManifest,
): string {
  return renderGeneratedModule(
    'catalogSyncManifest',
    'CatalogSyncManifest',
    catalogSyncManifest,
  );
}

export interface CatalogGeneratedArtifactPaths {
  manifestPath: string;
  snapshotPath: string;
}

export function getCatalogGeneratedArtifactPaths(
  workspaceRoot: string,
): CatalogGeneratedArtifactPaths {
  return {
    snapshotPath: resolve(workspaceRoot, GENERATED_SNAPSHOT_PATH),
    manifestPath: resolve(workspaceRoot, GENERATED_MANIFEST_PATH),
  };
}

export async function writeCatalogGeneratedArtifacts({
  catalogSnapshot,
  catalogSyncManifest,
  workspaceRoot,
}: {
  catalogSnapshot: CatalogSnapshot;
  catalogSyncManifest: CatalogSyncManifest;
  workspaceRoot: string;
}): Promise<CatalogGeneratedArtifactPaths> {
  const { manifestPath, snapshotPath } =
    getCatalogGeneratedArtifactPaths(workspaceRoot);

  await mkdir(dirname(snapshotPath), { recursive: true });
  await writeFile(snapshotPath, renderCatalogSnapshotModule(catalogSnapshot), 'utf8');
  await writeFile(
    manifestPath,
    renderCatalogSyncManifestModule(catalogSyncManifest),
    'utf8',
  );

  return {
    manifestPath,
    snapshotPath,
  };
}
